### ISSUE TITLE
Prepare back-end basic setup

### ISSUE THREAD

**Issue by murilopl** [murilopl/FliGuide#2]
### Tasks
- [x] Install Django Rest Framework
- [x] Replace user username to email
- [x] Create feature flag structure
